### ISSUE TITLE
Activating SUBBASINFLAG

### ISSUE THREAD

**Issue by dprincz** [MESH-Model/MESH-Dev#10]
As requested by @mee067. Implemented using 'ACLASS' approach while assigning basin information from file.

**Comment by mee067** [comment]
I ran successfully with the SUBBASINFLAG before but this time, I am getting an issue from the start. It counted 512 land tiles and is failing on tile 513!!

0BAD ITERATION TEMPERATURE        513      59            9.00  12   0
        0.0000      0.0000         NaN         NaN -19007.4980         NaN         NaN
0********  END  TSOLVE  ************************************************************************      -1

I am running from scratch (i.e. RESUMEFLAG 0).

Is that related to the basin outlet padding? The error is the same for 1860_ME_ZT and MESH_1.5.5
