### ISSUE TITLE
Considering `cmake` to add the capacity to compile `MESH` on Windows systems

### ISSUE THREAD

**Issue by kasra-keshavarz** [MESH-Model/MESH-Dev#40]
I thought it would be interesting to have `cmake` in `MESH` and have the capability to compile the program on Windows machines as well as *nix systems.

**Comment by dprincz** [comment]
MESH can be compiled for Windows machines using mingw-w64 via MSYS. Refer to the instructions and information [here](../wiki/Compiling-the-MESH-code#compiling-for-windows-using-mingw-w64-in-msys-with-gnugcc-and-gnugfortran)
