### ISSUE TITLE
Does the date of streamflow input file matter to the routing initialization process?

### ISSUE THREAD

**Issue by kasra-keshavarz** [MESH-Model/MESH-Dev#41]
This question was asked on Slack by @roalva82:

> does the date in the streamflow input file matters to initialize the routing?

And @mee067 answered:

> The start date of the streamflow input file does matter to initialization. If your simulation start before the start date on the streamflow input, channels will initialize as empty. Similarly, if the simulation starts after the date of the last entry of the input streamflow (it's a daily file so from the start date, it knows the end date), channels will initialize as empty. You normally get a warning in both cases. If the simulation date is within the range of the input, MESH will pick the corresponding values to initialize the channels.

Thought it would be good to permanently save it here for future users (if they happen to ask the same question).

**Comment by dprincz** [comment]
No. If there, it can be used to initialize channel storage. If resuming a run or if not desired, the file can contain no data and the channels would be initialized with zero storage.
