### ISSUE TITLE
Clarification with `Qo` and `Qi` output variables

### ISSUE THREAD

**Issue by kasra-keshavarz** [MESH-Model/MESH-Dev#42]
This question has been asked on Slack by @roalva82:

> I just wanted to double check something. Is QO the variable that corresponds to the routed discharge? I guess this would take values from ROF and route them through the channel network. Is this correct?

And, @mee067 answered:

> Qo is routed discharge at the grid level. it is based on ROF but it is already routed till the grid in question through the channels leading to that grid. Even local runoff in that grid is routed through an assumed channel. Qo is the streamflow leaving that grid to the next one. If you have a gauge at a specific grid, that's is the simulated streamflow that gets written to the streamflow file.

The explanation for the `Qo` and `Qi` needs a bit more clarity on the documentations.

Thought it would be good to permanently save the question/answer her for future users (if they happen to ask the same question).

**Comment by mee067** [comment]
Thanks for the documentation, Kasra.

To further clarify Qi, it is the routed streamflow from upstream grids/subs (you may have more than one) as it enters the channel before it gets routed through assumed within-grid/sub stream. I am not sure whether local grid/sub flow/runoff whether included or not?

Qi look very similar to Qo when plotted spatially.

**Comment by dprincz** [comment]
These are documented in the Variable List:
| Token | Description | Units | Minimum release | Notes |
| --- | --- | --- | --- | --- |
| RFF | Total runoff (from all surface, subsurface, and groundwater components). | mm | 1398 |   |
| ROF | Total runoff (from all surface and subsurface components). | kg m-2 | 1398 |   |
| QI | Flow rate entering the channel. | m3 s-1 | 1403 |   |
| QO | Flow rate leaving the channel (discharge). | m3 s-1 | 1403 |   |
| STGCH | Channel storage. | m3 | 1403 |   |
| ZLVL | Stage level. | m | 1403 |   |

**Comment by mee067** [comment]
this is still confusing - what is the difference between ROF and RFF? Kg/m2 is equivalent to mm - the table above means baseflow is not included in ROF but I do not think so. 

How does ZLVL get calculated?
