### ISSUE TITLE
What is the unit of precipitation forcing data?

### ISSUE THREAD

**Issue by kasra-keshavarz** [MESH-Model/MESH-Dev#53]
So, I have come across the following information on the wiki: 
<img width="837" alt="image" src="https://github.com/MESH-Model/MESH-Dev/assets/50383939/6b9884ee-145d-424b-866c-a8e420df3fad">
And
<img width="1668" alt="image" src="https://github.com/MESH-Model/MESH-Dev/assets/50383939/1fe117fc-8383-40bc-9a35-fcea6c340e6b">

What is the correct precipitation unit for `MESH`? Is it in $\frac{mm}{s}$ or $\frac{m}{s}$?

**Comment by mee067** [comment]
it is a mass flux unit: kg/m2/s - given that the density of water is 1000 kg/m3, this translates to mm/s if we consider an intensity (depth/time). This means the first table has a mistake.
