### ISSUE TITLE
crash when writing basin output

### ISSUE THREAD

**Issue by mee067** [MESH-Model/MESH-Dev#56]
Code compiled earlier - maybe a month or two ago did work. Re-compiled the same code (using intel 2018 and 2021), and I am getting strange crashes (Segmentation Fault). I recompiled with symbols on but only intel 2021 gives some clue, the 2018 compilation gave no info on where's the issue. This is the dump of the error:

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
mpi_sa_mesh_2021_  0000000000B6C8DA  Unknown               Unknown  Unknown
libpthread-2.30.s  00001555554270F0  Unknown               Unknown  Unknown
mpi_sa_mesh_2021_  0000000000AC7B0D  save_basin_output         946  save_basin_output.f90
mpi_sa_mesh_2021_  0000000000B44760  MAIN__                   1031  MESH_driver.f90
mpi_sa_mesh_2021_  000000000040CC92  Unknown               Unknown  Unknown
libc-2.30.so       0000155554726E1B  __libc_start_main     Unknown  Unknown
mpi_sa_mesh_2021_  000000000040CBAA  Unknown               Unknown  Unknown
```

This is a gridded setup. I first thought it has something to do with the LongSimFix but it does not. Line 946 of save_basin_output.f90 reads:
```
                    if (WF_RTE_fstflout%fout_hyd) write(iun, 1010, advance = 'no') &
                    fms%stmg%qomeas%val(i), out%d%grid%qo(fms%stmg%meta%rnk(i))
```

I did a bit of debugging and found that the rank of the third gauge went crazy to be 1112486707, while the basin only has 3448 active gridcells. 

Any ideas?

**Comment by mee067** [comment]
This crash is similar to the https://github.com/MESH-Model/MESH-Dev/issues/22

The same stupid number: 1112486707 got assigned to the rank gauge #3 - not sure where and how.

**Comment by dprincz** [comment]
@mee067 provided sample setup

**Comment by mee067** [comment]
somehow this seems to be related to resuming. runs starting with RESUMEFLAG 0 worked fine, runs starting with RESUMEFLAG 6 gave the above issue.

**Comment by dprincz** [comment]
It's telling me `fls` of the output file object `fls_out` isn't allocated:

![image](https://github.com/user-attachments/assets/8a83ab46-ea84-4232-8008-a409e2ffecbb)

I get the same result with `RESUMEFLAG 0`. I'll try to trace it up the line.

**Comment by dprincz** [comment]
Okay, the segmentation fault is coming because it goes to close the output files, but they haven't been opened or even configured yet.

Notice right before this:
```
 The simulation starts at: 2016/01/01 00:00:00.000000
 Checking the start dates of the input files...
   Skipping 189931 records in 'basin_shortwave.nc'.
   REMARK: Reached end of file reading 'rsds'.
   REMARK: Reached the end of the file in 'basin_shortwave.nc'.
   Skipping 189931 records in 'basin_longwave.nc'.
   REMARK: Reached end of file reading 'rlds'.
   REMARK: Reached the end of the file in 'basin_longwave.nc'.
   Skipping 189931 records in 'basin_rain.nc'.
   REMARK: Reached end of file reading 'pr'.
   REMARK: Reached the end of the file in 'basin_rain.nc'.
   Skipping 189931 records in 'basin_temperature.nc'.
   REMARK: Reached end of file reading 'ta'.
   REMARK: Reached the end of the file in 'basin_temperature.nc'.
   Skipping 189931 records in 'basin_wind.nc'.
   REMARK: Reached end of file reading 'wind'.
   REMARK: Reached the end of the file in 'basin_wind.nc'.
   Skipping 189931 records in 'basin_pres.nc'.
   REMARK: Reached end of file reading 'ps'.
   REMARK: Reached the end of the file in 'basin_pres.nc'.
   Skipping 189931 records in 'basin_humidity.nc'.
   REMARK: Reached end of file reading 'hus'.
   REMARK: Reached the end of the file in 'basin_humidity.nc'.
```
So the simulation doesn't run (i.e., `ENDDATA` is `.true.`).

To me, this doesn't have anything to do with the output files, but is an issue with skipping dates when opening the forcing files during initialization.

**Comment by dprincz** [comment]
I printed with `DIAGNOSEMODE`.
```
 The simulation starts at: 2016/01/01 00:00:00.000000
 Checking the start dates of the input files...
   INFO: The records in 'basin_shortwave.nc' start at: 1950/12/31 13:00:00.000000
   Skipping 189931 records in 'basin_shortwave.nc'.
   REMARK: Reached end of file reading 'rsds'.
   REMARK: Reached the end of the file in 'basin_shortwave.nc'.
   INFO: The records in 'basin_longwave.nc' start at: 1950/12/31 13:00:00.000000
   Skipping 189931 records in 'basin_longwave.nc'.
   REMARK: Reached end of file reading 'rlds'.
   REMARK: Reached the end of the file in 'basin_longwave.nc'.
   INFO: The records in 'basin_rain.nc' start at: 1950/12/31 13:00:00.000000
   Skipping 189931 records in 'basin_rain.nc'.
   REMARK: Reached end of file reading 'pr'.
   REMARK: Reached the end of the file in 'basin_rain.nc'.
   INFO: The records in 'basin_temperature.nc' start at: 1950/12/31 13:00:00.000000
   Skipping 189931 records in 'basin_temperature.nc'.
   REMARK: Reached end of file reading 'ta'.
   REMARK: Reached the end of the file in 'basin_temperature.nc'.
   INFO: The records in 'basin_wind.nc' start at: 1950/12/31 13:00:00.000000
   Skipping 189931 records in 'basin_wind.nc'.
   REMARK: Reached end of file reading 'wind'.
   REMARK: Reached the end of the file in 'basin_wind.nc'.
   INFO: The records in 'basin_pres.nc' start at: 1950/12/31 13:00:00.000000
   Skipping 189931 records in 'basin_pres.nc'.
   REMARK: Reached end of file reading 'ps'.
   REMARK: Reached the end of the file in 'basin_pres.nc'.
   INFO: The records in 'basin_humidity.nc' start at: 1950/12/31 13:00:00.000000
   Skipping 189931 records in 'basin_humidity.nc'.
   REMARK: Reached end of file reading 'hus'.
   REMARK: Reached the end of the file in 'basin_humidity.nc'.
```
`189931*3 = 569793` hours, `/= 24` `~= 23741` days, `/= 365.25` `~= 65` years, so to me the offset seems correct. My guess is that elsewhere, a variable used to check if the simulation has completed isn't initialized correctly.

**Comment by dprincz** [comment]
From this block of code, `ierr` must not be returning a normal status, which makes it jump to right after the simulation loop.
```
    !> Position the input forcing files to the current date.
    if (ro%RUNCLIM) then
        call skip_to_first_forcing_record(ierr)
        if (ierr /= 0) goto 97
    end if
```
The only place in `skip_to_first_forcing_record` I can see that would return a non-zero status without printing a message is the call to `mesh_io` to `read_frame_from_file`, but all that does is read data from the NetCDF file. Since those are all handled errors, I'll have to trace what's happening with inline print statements.

**Comment by dprincz** [comment]
The forcing files I have are concatenated... The code is behaving as expected noting the above, though a fail-safe could be added to avoid what I've documented. I'll re-review the sample to see if I can get the `save_basin_output` error.

**Comment by dprincz** [comment]
@mee067 I can't replicate the behavior with the sample provided. I changed the simulation start to 1951/001 based on the start date of the files and find it runs normally with `RESUMEFLAG 0`, `RESUMEFLAG 6`, and `RESUMEFLAG 6 auto`.

Can you provide me a fully-contained example where I shouldn't need to modify anything?

**Comment by mee067** [comment]
Setup and code sent by email. I see tgz is an accepted format but it still said "we won't support that file type". 12 MB is possibly too large for Github.

**Comment by dprincz** [comment]
One of the changes by MESH-Model/MESH_Code@52c7367 "LongSimFix" was to revise the use of `fhr` from tracking incremental hours in the simulation to always being equal to `1`.

When originally implemented, a temporary fix for observed variables arbitrarily allocated these arrays to `999999` blocks (observation hours). This caused issues for simulations exceeding 999999 hours (approx.. 114 years); for example, climate simulations from 1980 to 2100, which likely would cause an index out-of-bounds error in 2094 or later.

Changes by @mee067 to address this removed the allocation of these variables from `999999` to `(:, 1)`, setting the current record `fhr` always equal to `1`. However, the change only initialized `fhr = 1` when resumed from `seq` format resume files. `fhr` not being properly initialized without this condition seems to have contributed to the corruption of data used by the module, i.e., the record of observations index by gauge ID, causing the indexing issue observed with the streamflow observations printed by `save_basin_output`.

Adding the same condition, `fhr = 1`, during initialization resolves this issue.
```f90
!> Set fhr to 1 (the counting of incremental hours in the routing simulation is not used like it is in standalone WATROUTE).
fhr = 1
```

Further, additional modifications were made when resuming from the `seq` format resume files for the case when the file was written by a previous version of the code where `fhr /= 1`.
```f90
real(kind = 4), dimension(:, :), allocatable :: lake_elv_temp
...

if (fms%rsvr%n > 0) then
    allocate(lake_elv_temp(noresv, fhr))
    read(iun) lake_elv_temp(:, fhr)
    lake_elv(:, 1) = lake_elv_temp(:, fhr)
else
    read(iun)
end if
...

!> Set fhr to 1 (the counting of incremental hours in the routing simulation is not used like it is in standalone WATROUTE).
fhr = 1
```

**Comment by dprincz** [comment]
These changes are incorporated in dprincz/MESH-Dev@5fc2d3b.
