### ISSUE TITLE
[FLOODNET2] r1831_mod_2021-03-04+classz-can-errmsg for MESH - Ostrich

### ISSUE THREAD

**Issue by dprincz** [MESH-Model/MESH-Dev#64]
The [r1831_mod_2021-03-04+classz-can-errmsg.zip](https://github.com/user-attachments/files/16802215/r1831_mod_2021-03-04%2Bclassz-can-errmsg.zip) package should contain the updated static Windows executables for the modified code of 2b77c47 (r1813+mod_2021-03-04).

```
+ r1831_mod_2021-03-04+classz-can-errmsg
 + src (code)
 + bin
   - sa_mesh.netcdf-symbols.static.r1831_mod_2021-03-04+classz-can-errmsg.exe (serial+netcdf)
   - sa_mesh.netcdf-debug.static.r1831_mod_2021-03-04+classz-can-errmsg.exe (serial+netcdf, debug symbols)
   - mpi_sa_mesh.netcdf-symbols.static.r1831_mod_2021-03-04+classz-can-errmsg.exe (MS-MPI+netcdf)
```

Running the MPI version requires installation of [MS-MPI 10.1](https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html), though depending on the system might demonstrate degraded performance. If you have Admin access, you might wish to run it via WSL-Ubuntu using OpenMPI for this purpose instead, at least for iterative runs. For simple or isolated runs on Windows, I suggest using the regular `sa_mesh.exe` program instead.

Adds `I` to the error message printed for `CLASSZ -6` (and updates `6446 FORMAT` from `I8` to `2I8`) in [CLASSZ.f@2b77c47](https://github.com/dprincz/MESH-Dev/blob/2b77c475c1dc9d54384965eaab1b82b663942693/LSS_Model/CLASS/3.6/src/CLASSZ.f):
```f90
              WRITE(6,6446) N,I,WTVSTP(I),WSUMV
6446          FORMAT(2X,'CANOPY WATER BALANCE  ',2I8,2F20.8)
```

**Comment by mee067** [comment]
not sure why this is assigned to me!! If just for awareness, then thanks.
