### ISSUE TITLE
NetCDF resume files for vector-based setups

### ISSUE THREAD

**Issue by mee067** [MESH-Model/MESH-Dev#7]
I used SAVERESUMEFLAG 6 to save the resume file for a hot start for a vector-based setup. Using RESUMEFLAG 6 to read it failed on memory. Investigating the Initial conditions file, I found it has the wrong dimensions as n x n instead of n x 1, where n is the number of subbasins.

**Comment by mee067** [comment]
I fixed the issue in this code:
https://github.com/MESH-Model/MESH_Code/tree/master

**Comment by dprincz** [comment]
Pending update from r1680_ME.
